name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.0-beta2"

      - name: Install dependencies for @halimath/scenic
        working-directory: ./scenic
        run: npm i

      - name: Build @halimath/scenic
        working-directory: ./scenic
        run: npm run build

      - name: Install dependencies for @halimath/battlemap
        working-directory: ./battlemap
        run: npm i

      - name: Build @halimath/battlemap
        working-directory: ./battlemap
        run: npm run build

      - name: Install dependencies for app
        working-directory: ./app
        run: npm i

      - name: Build app
        working-directory: ./app
        run: npm run build

      - name: Copy static assets
        working-directory: ./backend
        run: cp -r ../app/dist ./internal/boundary/public

      - name: Build backend
        working-directory: ./backend
        run: go build

      - name: Run backend tests
        working-directory: ./backend
        run: go test -cover ./...
